<?php $banner = $this->getCurrentBanner();    ?>
<?php if ($banner): ?>
    
    <h1><?php echo $banner->getTitle(); ?></h1>
    <p><a href="<?php echo $this->helper('ap_modbanners/banner')->getBannerUrl($banner); ?>" title="<?php echo $this->escapeHtml($banner->getName()); ?>"><?php echo $banner->getTitle(); ?></a></p>
    <?php echo $banner->getDescription(); ?>
    <p><a href="<?php echo $this->getUrl('ap_modbanners/index/index') ?>" title="<?php echo $this->__('Back to banners list'); ?>"><?php echo $this->__('&laquo; Back to banners list'); ?></a></p>
    
     
    
    
<?php endif; ?>
